### ISSUE TITLE
Port Octopus Server to .NET Core

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/Issues#2696]
This issue will cover the port to .NET Core, but not the further work required to run on Linux. Tentacle side of this is in #3501

## Octopus Server
- [ ] Find alternatives to `Image` `Bitmap` (may be supported in netstandard2.0 now)
- [ ] Convert to Nancy 2.0 or ASP.NET Core
- [ ] Figure out if we can use the portable version of Bouncy Castle (for certificates)
- [ ] WebSockets support
- [x] DbUp
- [ ] Do AWS libs work?
- [ ] Do Azure libs work?
- [ ] Alternative to MachineKey

## UserVoice References

UserVoice: https://octopusdeploy.uservoice.com/forums/170787-general/suggestions/10783866-port-octopus-to-net-core

## Notes

@michaelnoonan discovered newer versions of Nancy cause us to double-HTML-decode cookies which makes the authentication code fail mysteriously. This is something to keep an eye on when upgrading Nancy.

**Comment by vikaschenny** [comment]
anyone can you share installation octopus in ubuntu.

**Comment by droyad** [comment]
We are working on this for an internal need. We plan on releasing it publicly as a beta at the end of that work. While the core application will be stable, some features will be missing (e.g. AD Integration, Run on Server, WebSocket Tentacles) and the install and management experience is will not be as smooth as the Windows version.

Whether we move to full release will depend on customer feedback.

**Comment by nunoguerreirorosa** [comment]
Any news regarding octopus server on linux ?

**Comment by droyad** [comment]
@nunoguerreirorosa Not right now, but subscribe to #6049 to stay updated

**Comment by droyad** [comment]
This has been completed and is being used internally. I've created #6049 to track the public release of this (however we have not committed to working on it yet)
