### ISSUE TITLE
Tentacle Health Check, Communication and Deployment Hang Issues

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/Issues#3172]
This is a overview issue for Tentacle communication and deployment hang issues.

If you are experiencing this kind of issue, please upgrade to the latest version as fixes are rolling out regularly along with logging improvements. When contacting support, please send the [server](https://octopus.com/docs/reference/log-files), tentacle and [tasks](https://octopus.com/docs/how-to/how-to-turn-on-variable-logging-and-export-the-task-log) logs to support.

## Issue overview:

Also see #3113 Performance degradation reported for large installations after upgrading to Octopus 3.7

- [x] [Forum](http://help.octopusdeploy.com/discussions/problems/51139) #3190 `3.11.2` - When the octopus server restarts, polling tentacles do not reconnect
- [ ] [Forum](http://help.octopusdeploy.com/discussions/problems/51141) - Health check hangs after adding a large number of machines possibly related to #3190 or #3238
- [ ] [Forum](http://help.octopusdeploy.com/discussions/problems/51312) - Tasks wait for access to a tentacle despite nothing else running. Possible zombie task on the tentacle. Health check will also not fully cancel (#3175 and possibly #3238).
- [x] `3.11.2` When there are a high number steps running at the same time, the server would become unresponsive
- [x] #2971 Tasks sometimes get stuck in the "Cancelling" state
- [ ] #3078 Package transfer is not stopped when task is cancelled
- [ ] #3079 Tentacle package download is not stopped when a task is cancelled
- [x] #3142 `3.8.8` Allow health checks to skip machines that can not be checked because they are currently involved in a deployment
- [x] #3151 #3156 `3.8.8` Deployment where causing the server to run out of SQL connections
- [x] #3289 SSH Targets may be hanging on certain output - Looks like it is caused by malformed `##octopus` directives
- [ ] #3204 Deployment hangs on extracting package 
- [x] [Forum](http://help.octopusdeploy.com/discussions/problems/51600) Server successfully connects to a tentacle every second. **Resolved** Pool timeout was set to 0. Unsure why the server was sending something every second.
- [x] #3273 The deployment may appear to hang if an error occurs writing to the task log file. The deployment slows down to a snails pace and there is no feedback to the user.

### Hanging Cancellation
In Octopus  `3.8.5` we implemented #3098 "Upon cancellation tasks now wait until all sub tasks are complete before being marked as cancelled". Previously it was just abandoning them. This means that hung/slow background tasks were just left running, causing unexpected side effects. We expect that we will get more reports of tasks that fail to cancel.

### Communication
In Octopus `3.8.6` we improved communication and logging for server-tentacle communication (#3121, #2914).

### Health Checks
In Octopus `3.8.8` we improved the locking during Health check and cancellation of those checks (#3142).

**Comment by droyad** [comment]
Fix to Health Checks hanging https://github.com/OctopusDeploy/Issues/issues/3203

**Comment by droyad** [comment]
`3.11.2`  Improved server resource usage with hundreds of polling tentacles #3190

**Comment by droyad** [comment]
When reconfiguring tentacles (eg with `register-with`) ensure the tentacle is restarted.

**Comment by droyad** [comment]
Closing as it looks like we've gotten over this hill, no recent reports.
