### ISSUE TITLE
Port Octopus Server to Linux

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/Issues#3743]
Split issue from #2696 (OD on .NET Core)
Related to #3596 (Tentacle on Linux)

Server on Linux UserVoice: https://octopusdeploy.uservoice.com/forums/170787-general/suggestions/11388033-install-octopus-server-on-linux

Main things to address
- [x] External worker so we can run all steps
- [ ] #2696 (OD on .NET Core) needs to be completed
- [ ] How do we handle storing the master key? (ie is MachineKey available)
- [ ] Some of the Certificate management APIs are missing on .net core
- [ ] How would the service be installed?
- [x] Can we run our existing PowerShell scripts (for run-on-server steps)? (eg Azure deployment)
- [ ] Change file system access

**Comment by droyad** [comment]
This has been completed and is being used internally. I've created #6049 to track the public release of this (however we have not committed to working on it yet)
