### ISSUE TITLE
Account Usage does not show all usages

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/Issues#4675]
I found a few problems:
- [x] [This](https://github.com/OctopusDeploy/OctopusDeploy/blob/7ecdba3bafb585acc2aa2da3bcc5268f978a0947/source/Octopus.Server/Web/Api/Actions/AccountUsageListAction.cs#L278) line should be `Id`, not `OwnerId`
- [x] All account types should show usages for VariableSets, Project, DeploymentProcess and Releases as the delete checks the JSON (or related documents in the new code) for any occurrence of the ID. - fixed by https://github.com/OctopusDeploy/Issues/issues/5658
- [x] The UI does not show anything if a account is in a variable set belonging to a release but has since been removed from the project (see 1) below - fixed by https://github.com/OctopusDeploy/Issues/issues/4917
- [x] The API does not return anything if the account is only used in a deployment variable set (see 2) - fixed by https://github.com/OctopusDeploy/Issues/issues/5653
- [ ] ~Accounts used in steps in places other than specific account fields are not reported (see 3)~
- [x] Token account usage is returned from the api, but not shown - fixed by https://github.com/OctopusDeploy/Issues/issues/5630

# Discussions Related to this:
https://octopusdeploy.slack.com/archives/C8TV070E6/p1529985393000047
https://octopusdeploy.slack.com/archives/C033W4273/p1529301476000156
https://octopusdeploy.slack.com/archives/C033W4273/p1529301575000080
https://octopusdeploy.slack.com/archives/CG4JP65N2/p1550715679008900

## 1. Release only
1. Add a variable to a project's variable set
2. Create a release
3. Remove the variable from the variable set

The `Usages` API now returns:
```
{
  "Targets": [],
  "DeploymentProcesses": [],
  "Releases": [],
  "ProjectVariableSets": [
    {
      "ProjectSlug": "azure",
      "ProjectName": "Azure",
      "ProjectId": "Projects-21",
      "Releases": [
        {
          "ReleaseId": "Releases-141",
          "ReleaseVersion": "0.0.10"
        }
      ],
      "IsCurrentlyBeingUsedInProject": false
    }
  ],
  "LibraryVariableSets": [],
  "Links": {}
}
```

The `IsCurrentlyBeingUsedInProject` causes the entry to be ignored by the UI in the "project" section. I'm unsure whether it should appear in the `DeploymentProcesses` or `Releases` collections, these seem to be driven off usage in `DeploymentProcess` and not `VariableSet`

## 2. Deployment only
This one is a bit more of a corner case. After the steps in 1 above:
4. Deploy the release
5. Update the variable snapshot for the release (which removes the variable as it's no longer on the project

The `Usage` API now returns everything as empty.

Note that #4676 issue is orphaning the Release variable snapshot. However the deployment manifest variables (`VariableSet WHERE OwnerId like 'Deployments%'`) still legitimately exits, can could be involved in another deployment (or be a running deployment)

An alternative method of arriving at this is to perform a deployment to an Azure target with an account. The AccountId is collected into the deployment manifest. Deletion is now prevented due to the JSON serach, but the `Usage` API does not report it.

## 3. Non-Account fields in deployment process

** Update** I misunderstood the code here, deletion is not prevented if used in non-well-known fields.

~~[This](https://github.com/OctopusDeploy/OctopusDeploy/blob/master/source/Octopus.Core/Persistence/Indexes/Relationships/AccountRelationships.cs#L49) code only looks at specific properties when getting in-use accounts. However the "is in use" check a few lines earlier searches the whole JSON. So if the account variable is in any other field, deletion is prevented, but it is not reported in usage.~~

~~We either need to relax the delete rule, or return all ids~~

**Comment by droyad** [comment]
Ok, looking at the code again for #3. I think the deletion is NOT prevented for use outside the designated fields as the first part is a rought SQL filter, then refined by the second even for deletion

**Comment by wgv-srsedate** [comment]
We also have this issue, and are running Octopus v2018.8.4.  We had opened a topic on the issue.

https://help.octopus.com/t/cannot-delete-account-variable-reference/21241

**Comment by wgv-srsedate** [comment]
This is still an issue, and we have hundreds of accounts that we are unable to delete.  Is there any progress on this issue?  It looks like it might be related to account relationships with tenants.

**Comment by wgv-srsedate** [comment]
This is still an issue, and we have not heard any updates.  We have hundreds of accounts that we still need to delete, and there is no information or workaround in the system.  Some of these accounts allow you to delete them if you also delete the associated tenant (even if you've already unlinked the tenant from the account), but not all of our accounts were tenanted to begin with.  Can we get an update on the progress for a fix?

**Comment by KennethBates** [comment]
Something else relevant here is I cannot delete a username/password account if it has been used in an SSH target I've deployed a release to, even if I delete the SSH target or change the account used on that target.

The steps I took to reproduce:
1) Used this username/password account as auth for an SSH target
2) Deployed to that SSH target
3) Change SSH target user or delete the target
4) Try to delete the old user

Result: I can't delete the account until I delete that release, but the account usage only shows targets that use this account and not individual releases. Error message: `This account cannot be deleted as it is currently referenced by a variable. Please refer to account usage for more detail.`

Source: https://secure.helpscout.net/conversation/783543903/39656?folderId=954335 (private link)

**Comment by maartenmensink** [comment]
Any updates on this issue? We are facing the same problem. 

Calling /api/accounts/sshkeypair-test1234/usages shows no usages of the account but still unable to delete the account.

```
{
  "Targets": [],
  "DeploymentProcesses": [],
  "Releases": [],
  "ProjectVariableSets": [],
  "LibraryVariableSets": [],
  "Links": {}
}
```

**Comment by rwkarg** [comment]
Same issue. Create a k8s service account token and a target, do a deploy, delete target (cluster itself has externally been deleted), delete account --> DOES NOT DELETE

UI shows no usages of the account.

We're not yet at hundreds of accounts but we're on our way there.

**Comment by droyad** [comment]
Related to #4319

**Comment by droyad** [comment]
While #4917 seems to have fixed #1 above, there is another scenario: 
1. Create an account
1. Create a target that uses the account
1. Deploy to the target
1. Change the target to use a different account

The original account can't be deleted:
![image](https://user-images.githubusercontent.com/1687639/60305953-c36c5b00-9981-11e9-8d1c-63aac88c2bec.png)

**Comment by droyad** [comment]
Work around is to delete the release (e.g. though retention policies) that used those accounts.

**Comment by matt-richardson** [comment]
From what we can tell, all known bugs are resolved, as of `2019.7.0`.
If you find any occurences where usage is not accurate, please get in touch with us via our [support channels](https://octopus.com/support)
