### ISSUE TITLE
Extend failed login tracker to support API keys

### ISSUE THREAD

**Issue by matt-richardson** [OctopusDeploy/Issues#5139]
# Prerequisites

- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this feature request
- [x] I have tagged the issue appropriately (area/*, kind/enhancement)

# The enhancement

We currently have brute force protection in place for user logins - too many failed logins and that account will be blocked for a period of time. We should extend this to API Keys, and block requests from IP addresses who are determined to be attempting a brute force attack

## Workarounds

About the best workaround at this point is using a WAF or similar to track failed authentication attempts.

## Links

Source: internally raised
