### ISSUE TITLE
Format tasks by ending entries with '.' and fixing `1 machines`

### ISSUE THREAD

**Issue by mudra-octopus** [OctopusDeploy/Issues#5437]
# Prerequisites

- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested
- [x] I have written a descriptive issue title
- [ ] I have linked the original source of this feature request
- [x] I have tagged the issue appropriately (area/*, kind/enhancement)

# The enhancement

Some of the task log entries are not formatted properly. 

Task log looks like: 
`Starting health check for a limited set of machines 
1 machines will have their health checks taken. `

On reading it seems like 1 sentence and also grammatically incorrect. 

Suggest we try to modify it like: 

Starting health check for a limited set of **machines.**
**1 machine** will have their health checks taken. 

## Task Link: 
https://mudra.octopushq.com/app#/Spaces-1/tasks/ServerTasks-5140?activeTab=taskLog

## Screenshot: 
![image](https://user-images.githubusercontent.com/48192575/55309005-c6010680-549f-11e9-9ff5-57907ce6afcf.png)

**Comment by octoreleasebot** [comment]
Release Note: Updated health check messages to better reflect plural and singular
