### ISSUE TITLE
Add connectivity checks for Jira issue tracker

### ISSUE THREAD

**Issue by hnrkndrssn** [OctopusDeploy/Issues#5771]
**_Are you a customer of Octopus Deploy? Don't raise the issue here. Please contact [our support team](https://octopus.com/support) so we can triage your feature request, making sure it's handled appropriately._**

# Prerequisites

- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested
- [x] I have discussed this in #feature-discussion or #backlog and the consensus is that this is something we plan on adding in the near future
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this feature request
- [x] I have tagged the issue appropriately (area/*, kind/enhancement)

# The enhancement

## What is the problem this solves or benefit it gives

Currently there is no way to easily check if you've configured all the necessary pieces correctly for the Jira integration to work successfully when you push package metadata to Octopus to your performing a deployment that pushes deployment information to Jira.

## Proposed solution

We should add a button that allows testing the connectivity between our Jira connect app and Octopus (used to push deployment info to Jira) and also between Octopus and your Jira instance (used to pull issue titles/release notes from your Jira instance).

## Mockup

![JiraConnectivityTest](https://user-images.githubusercontent.com/1035315/62849862-9b17a080-bd24-11e9-9c6a-247d6045c9f9.gif)

## Workarounds

NA

**Comment by octoreleasebot** [comment]
Release Note: Add connectivity verification buttons for Jira issue tracker settings
