### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by jess-ross** [OctopusDeploy/Issues#6192]
# Prerequisites

- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested
- [x] I have discussed this in #feature-discussion or #backlog and the consensus is that this is something we plan on adding in the near future
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this feature request
- [x] I have tagged the issue appropriately (area/*, kind/feature)

# The feature

## What it actually enables people to do

User will be able to enable dark theme for personal preferences of aesthetics, reduce eye strain and for better visibility in low light environments. The dark theme can be enabled manually but will automatically be enabled if a user has dark theme selected for their OS.

### Mockup
<img width="1450" alt="Screen Shot 2020-02-21 at 10 46 55 am" src="https://user-images.githubusercontent.com/17240784/74993683-80727100-5497-11ea-9520-956be0176004.png">

## What pain relievers or gain generators are we solving for people?

- Eye strain
- Use of Octopus in low-light environments
- Catering for personal aesthetic preferences

## What this feature isn't

Although we have adhered to a contrast ratio of AA standard and have considered accessibility, low-light environment viewing and glow around text, it is not an accessibility theme.

## Who will care about it?

On User Voice, dark theme has 160 votes and we know a lot of our users prefer a dark color scheme when working. 

## Elevator pitch for this feature

Octopus can now be used in the dark, reducing eye strain and more aesthetically pleasing to your personal preference. 

## How much noise should we make about this?

We plan to make lots of noise about this feature.

# Links

https://octopusdeploy.uservoice.com/forums/170787-general/suggestions/31871626-dark-theme

**Comment by octoreleasebot** [comment]
Release Note: Enable Dark Theme
