### ISSUE TITLE
Add support for configuring multiple connection for Azure DevOps Issue Tracker integration

### ISSUE THREAD

**Issue by johnsimons** [OctopusDeploy/Issues#7209]
**_Are you a customer of Octopus Deploy? Don't raise the issue here. Please contact [our support team](https://octopus.com/support) so we can triage your feature request, making sure it's handled appropriately._**

# Prerequisites

- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested
- [x] I have discussed this in #feature-discussion or #backlog and the consensus is that this is something we plan on adding in the near future
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this feature request
- [x] I have labelled the value stream (area/core, area/steps, ...)
- [x] I have added the kind/enhancement label

# The enhancement

## What is the problem this solves or benefit it gives
Back when we build the functionality to associate Build Information with packages we hadn't planned for customers that have access to more than one Azure DevOps organisation and hence we only added support to associate a single Azure DevOps organisation. This is a limitation that we are now addressing.

## Proposed solution
Add the option for Azure DevOps work item tracking integration to be configured with multiple Azure DevOps organisation urls, which means we will be able to show work items from more than one Azure DevOps organisation as part of release creation or when looking at a package metadata.

## Mockup
![image](https://user-images.githubusercontent.com/122651/143504705-ed4ae419-eb39-434e-a886-5430a9ce0b0f.png)

## Workarounds
None

**Comment by johnsimons** [comment]
Release Note: Added support for configuring multiple connection for Azure DevOps Issue Tracker integration

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.8857 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.8857 |
| 2022.1+ | _all releases_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.0 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.8857 |
| 2022.1+ | _all releases_ |
